from __future__ import annotations

import io
import json
from pathlib import Path
import sqlite3
import subprocess
import zipfile

import pytest

from scripts import oliver_smoke_upgrade as smoke


def _wheel(path: Path, *, version: str = "0.19.0", extra: str = "") -> Path:
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr(
            f"algo_cli_runtime-{version}.dist-info/METADATA", f"Name: algo-cli-runtime\nVersion: {version}\n"
        )
        if extra:
            archive.writestr(extra, "")
    return path


def test_candidate_version_and_experimental_scope_are_checked(tmp_path):
    path = _wheel(tmp_path / "candidate.whl")
    smoke.validate_candidate(path, "0.19.0")
    for version in ("0.18.0", "0.20.0"):
        with pytest.raises(ValueError, match="source version"):
            smoke.validate_candidate(path, version)
    for module in smoke.EXCLUDED_MODULES:
        _wheel(path, extra=module)
        with pytest.raises(ValueError, match="excluded verifier"):
            smoke.validate_candidate(path, "0.19.0")


def test_isolation_does_not_inherit_provider_credentials_or_installer_settings(tmp_path, monkeypatch):
    for key in ("OPENAI_API_KEY", "OLLAMA_API_KEY", "PYTHONPATH", "PIP_EXTRA_INDEX_URL", "UV_INDEX", "ALGO_CLI_CWD"):
        monkeypatch.setenv(key, "synthetic-inherited-value")
    monkeypatch.setenv("ALGO_CLI_CONFIG_DIR", str(tmp_path / "real-state"))
    env = smoke.isolated_environment(tmp_path / "home", tmp_path / "bin")
    assert env["ALGO_CLI_CONFIG_DIR"] == str(tmp_path / "home" / ".algo_cli")
    assert "synthetic-inherited-value" not in env.values()
    assert env["PYTHON_KEYRING_BACKEND"] == "keyring.backends.null.Keyring"
    assert env["PIP_INDEX_URL"] == "https://pypi.org/simple"


def test_offline_update_environment_uses_supported_uv_controls_and_escaped_paths(tmp_path):
    wheelhouse = tmp_path / "wheel house, with spaces"
    cache = tmp_path / "private-cache"
    online = {"PIP_INDEX_URL": "https://pypi.org/simple"}
    env = smoke.offline_update_environment(online, wheelhouse, cache)
    assert online == {"PIP_INDEX_URL": "https://pypi.org/simple"}
    assert env["PIP_NO_INDEX"] == "1"
    assert env["UV_OFFLINE"] == "true"
    assert "UV_NO_INDEX" not in env
    assert env["UV_NO_CONFIG"] == "true"
    assert env["UV_CACHE_DIR"] == str(cache)
    assert env["UV_PYTHON_DOWNLOADS"] == "never"
    assert env["PIP_FIND_LINKS"] == env["UV_FIND_LINKS"] == wheelhouse.resolve().as_uri()
    assert " " not in env["UV_FIND_LINKS"] and "," not in env["UV_FIND_LINKS"]


def _installed_wheel(tmp_path):
    wheel = _wheel(tmp_path / "candidate.whl")
    with zipfile.ZipFile(wheel, "a") as archive:
        archive.writestr("algo_cli/__init__.py", '__version__ = "0.19.0"\n')
        archive.writestr("algo_cli/updater.py", "# candidate implementation\n")
        archive.writestr("ollama_cli/__init__.py", "# compatibility package\n")
        archive.writestr("algo_cli_runtime-0.19.0.dist-info/RECORD", "installer rewrites this\n")
    env_dir = tmp_path / "env"
    site = env_dir / "site-packages"
    with zipfile.ZipFile(wheel) as archive:
        archive.extractall(site)
    return wheel, env_dir, site


def test_installed_wheel_checks_payload_without_rejecting_installer_generated_files(tmp_path):
    wheel, _, site = _installed_wheel(tmp_path)
    metadata = site / "algo_cli_runtime-0.19.0.dist-info"
    (metadata / "RECORD").write_text("rewritten by installer\n")
    (metadata / "INSTALLER").write_text("uv\n")
    cache = site / "algo_cli/__pycache__"
    cache.mkdir()
    (cache / "__init__.cpython-312.pyc").write_bytes(b"generated bytecode")
    assert smoke.verify_installed_wheel(wheel, site) == 4


@pytest.mark.parametrize("change", [
    "different-bytes", "missing", "extra-source", "extra-bytecode", "metadata", "legacy-bytes", "legacy-extra",
])
def test_installed_wheel_rejects_same_version_substitution_and_incomplete_replacement(tmp_path, change):
    wheel, _, site = _installed_wheel(tmp_path)
    if change == "different-bytes":
        (site / "algo_cli/updater.py").write_text("# other build with the same version\n")
    elif change == "missing":
        (site / "algo_cli/updater.py").unlink()
    elif change == "extra-source":
        (site / "algo_cli/obsolete.py").write_text("# leftover from predecessor\n")
    elif change == "extra-bytecode":
        (site / "algo_cli/obsolete.pyc").write_bytes(b"unverified sourceless module")
    elif change == "legacy-bytes":
        (site / "ollama_cli/__init__.py").write_text("# different compatibility package\n")
    elif change == "legacy-extra":
        (site / "ollama_cli/obsolete.py").write_text("# leftover compatibility module\n")
    else:
        (site / "algo_cli_runtime-0.19.0.dist-info/METADATA").write_text(
            "Name: algo-cli-runtime\nVersion: 0.19.0\nSummary: other build\n"
        )
    with pytest.raises(ValueError, match="installed wheel"):
        smoke.verify_installed_wheel(wheel, site)


@pytest.mark.parametrize("name", ["../escaped", "algo_cli/../escaped", "/absolute", "unexpected.data/file"])
def test_installed_wheel_rejects_unsupported_archive_paths(tmp_path, name):
    wheel, _, site = _installed_wheel(tmp_path)
    with zipfile.ZipFile(wheel, "a") as archive:
        archive.writestr(name, "invalid payload")
    with pytest.raises(ValueError, match="installed wheel"):
        smoke.verify_installed_wheel(wheel, site)


def test_installed_identity_verifies_actual_wheel_and_reports_version_mismatch(tmp_path, monkeypatch):
    wheel, env_dir, site = _installed_wheel(tmp_path)
    identity = {
        "metadata": "0.19.0", "runtime": "0.19.0", "manager": "pip",
        "file": str(site / "algo_cli/__init__.py"), "site": str(site),
    }
    monkeypatch.setattr(smoke, "run", lambda *args, **kwargs: json.dumps(identity))
    assert smoke.installed_identity(Path("python"), env_dir, "0.19.0", {}, tmp_path, wheel=wheel) == 4
    identity["metadata"] = identity["runtime"] = "0.19.1.post1"
    with pytest.raises(ValueError, match="expected 0.18.0.*0.19.1.post1"):
        smoke.installed_identity(Path("python"), env_dir, "0.18.0", {}, tmp_path, wheel=wheel)


@pytest.mark.parametrize("surface", ["site", "file"])
def test_installed_identity_rejects_package_or_metadata_outside_isolation(tmp_path, monkeypatch, surface):
    wheel, env_dir, site = _installed_wheel(tmp_path)
    identity = {
        "metadata": "0.19.0", "runtime": "0.19.0", "manager": "pip",
        "file": str(site / "algo_cli/__init__.py"), "site": str(site),
    }
    identity[surface] = str(tmp_path / "outside")
    monkeypatch.setattr(smoke, "run", lambda *args, **kwargs: json.dumps(identity))
    with pytest.raises(ValueError, match="isolated installation"):
        smoke.installed_identity(Path("python"), env_dir, "0.19.0", {}, tmp_path, wheel=wheel)


@pytest.mark.parametrize("failure", ["baseline", "candidate"])
def test_failure_receipt_only_claims_a_completed_updater_call(tmp_path, monkeypatch, failure):
    wheel = _wheel(tmp_path / "candidate.whl")
    report = tmp_path / "failure.json"
    commands = []
    monkeypatch.setattr(smoke.sys, "platform", "linux")
    monkeypatch.setattr(smoke, "_wheel_from", lambda _: wheel)
    monkeypatch.setattr(smoke, "_source_version", lambda: "0.19.0")
    monkeypatch.setattr(smoke, "download_baseline", lambda _: None)
    monkeypatch.setattr(smoke, "_create_isolated_environment", lambda env_dir: (
        env_dir / "bin/python", ["python", "-m", "pip", "install"],
    ))
    monkeypatch.setattr(smoke, "run", lambda command, **kwargs: commands.append(command) or "")

    def identity(python, env_dir, expected, *args, **kwargs):
        baseline = expected == smoke.BASELINE_VERSION
        if baseline == (failure == "baseline"):
            raise ValueError("synthetic identity failure")
        return 251

    monkeypatch.setattr(smoke, "installed_identity", identity)
    with pytest.raises(ValueError, match="synthetic identity failure"):
        smoke.main([str(wheel), "--report", str(report)])
    receipt = json.loads(report.read_text())
    assert receipt["status"] == "failed"
    assert any(command[-1] == "update" for command in commands) == (failure == "candidate")
    assert receipt["published_updater_exercised"] == (failure == "candidate")


@pytest.mark.parametrize("surface", ["config.json", "chatgpt_auth.json", "memory.json", "private/opaque-state.bin"])
def test_state_manifest_detects_changed_user_state(tmp_path, surface):
    home, work = tmp_path / "home", tmp_path / "work"
    home.mkdir()
    work.mkdir()
    smoke.seed_state(home, work)
    before = smoke.state_manifest(home, work)
    assert json.loads((home / ".algo_cli" / "config.json").read_text())["cwd"] == str(work)
    (home / ".algo_cli" / surface).write_bytes(b"changed")
    assert smoke.state_manifest(home, work) != before


def test_state_manifest_detects_workspace_changes_and_missing_files(tmp_path):
    home, work = tmp_path / "home", tmp_path / "work"
    home.mkdir()
    work.mkdir()
    smoke.seed_state(home, work)
    before = smoke.state_manifest(home, work)
    (work / "kept.txt").unlink()
    assert smoke.state_manifest(home, work) != before


def test_wrong_published_baseline_digest_is_rejected(tmp_path, monkeypatch):
    monkeypatch.setattr(smoke, "urlopen", lambda *args, **kwargs: io.BytesIO(b"not the published wheel"))
    path = tmp_path / "baseline.whl"
    with pytest.raises(ValueError, match="pinned PyPI digest"):
        smoke.download_baseline(path)
    assert not path.exists()


def test_seed_state_closes_sqlite_connection_before_returning(tmp_path, monkeypatch):
    connections = []
    connect = sqlite3.connect

    def tracked_connect(*args, **kwargs):
        connection = connect(*args, **kwargs)
        connections.append(connection)
        return connection

    monkeypatch.setattr(smoke.sqlite3, "connect", tracked_connect)
    home, work = tmp_path / "home", tmp_path / "work"
    home.mkdir()
    work.mkdir()
    smoke.seed_state(home, work)
    assert len(connections) == 1
    with pytest.raises(sqlite3.ProgrammingError, match="closed database"):
        connections[0].execute("SELECT 1")


def test_windows_upgrade_uses_external_owning_manager_from_public_install(tmp_path, monkeypatch):
    monkeypatch.setattr(smoke.sys, "platform", "win32")
    expected = ["isolated-python", "-m", "pip", "install", "--upgrade", "algo-cli-runtime"]
    calls = []

    def run(command, **kwargs):
        calls.append(command)
        return json.dumps(expected)

    monkeypatch.setattr(smoke, "run", run)
    assert smoke.upgrade_command(Path("isolated-python"), Path("algo-cli.exe"), {}, tmp_path) == expected
    assert calls[0][:3] == ["isolated-python", "-I", "-c"]
    assert "build_update_plan" in calls[0][3]


@pytest.mark.parametrize("platform", ["linux", "darwin"])
def test_posix_upgrade_exercises_the_actual_published_cli(tmp_path, monkeypatch, platform):
    monkeypatch.setattr(smoke.sys, "platform", platform)
    monkeypatch.setattr(smoke, "run", lambda *args, **kwargs: pytest.fail("must use actual CLI"))
    assert smoke.upgrade_command(Path("python"), Path("algo-cli"), {}, tmp_path) == ["algo-cli", "update"]


@pytest.mark.parametrize("payload", ["{}", "[]", '["python", null]', '[""]'])
def test_windows_upgrade_rejects_invalid_manager_command(tmp_path, monkeypatch, payload):
    monkeypatch.setattr(smoke.sys, "platform", "win32")
    monkeypatch.setattr(smoke, "run", lambda *args, **kwargs: payload)
    with pytest.raises(ValueError, match="owning-manager command"):
        smoke.upgrade_command(Path("python"), Path("algo-cli.exe"), {}, tmp_path)


@pytest.mark.parametrize("returncode,output,accepted", [
    (64, "cannot replace its running Windows launcher. PowerShell:", True),
    (0, "cannot replace its running Windows launcher. PowerShell:", False),
    (64, "different failure", False),
])
def test_windows_launcher_probe_requires_the_specific_guard(tmp_path, monkeypatch, returncode, output, accepted):
    monkeypatch.setattr(
        smoke.subprocess, "run",
        lambda command, **kwargs: subprocess.CompletedProcess(command, returncode, stdout=output, stderr=""),
    )
    if accepted:
        smoke.verify_windows_launcher_guard(Path("algo-cli.exe"), {}, tmp_path)
    else:
        with pytest.raises(ValueError, match="refuse unsafe self-replacement"):
            smoke.verify_windows_launcher_guard(Path("algo-cli.exe"), {}, tmp_path)


def test_windows_launcher_probe_retains_bounded_failure_diagnostics(tmp_path, monkeypatch):
    monkeypatch.setattr(smoke.subprocess, "run", lambda command, **kwargs: subprocess.CompletedProcess(
        command, 1, stdout="x" * 9000, stderr="migration blocked",
    ))
    with pytest.raises(ValueError) as exc:
        smoke.verify_windows_launcher_guard(Path("algo-cli.exe"), {}, tmp_path)
    assert '"returncode": 1' in str(exc.value)
    assert "migration blocked" in str(exc.value)
    assert len(str(exc.value)) < 4500


def test_ci_requires_upgrade_on_every_installed_platform():
    workflow = (smoke.ROOT / ".github/workflows/oliver-ci.yml").read_text(encoding="utf-8")
    job = workflow.split("  package-smoke:\n", 1)[1]
    assert "os: [ubuntu-latest, windows-latest, macos-latest]" in job
    assert "python scripts/oliver_smoke_upgrade.py dist" in job
    for manager in ("pip", "pipx", "uv"):
        assert (
            f"run: python scripts/oliver_smoke_upgrade.py dist --manager {manager} "
            f"--report upgrade-smoke-{manager}.json"
        ) in job
    assert "if: always()" in job
    assert (
        "run: python scripts/oliver_smoke_upgrade.py dist --manager pipx "
        "--pipx-backend uv --report upgrade-smoke-pipx-uv.json"
    ) in job
