"""Repository intelligence data structures and index builders."""

from .project_graph import (
    FileNode,
    ImportEdge,
    ProjectGraph,
    SymbolNode,
    TestMapping,
    build_project_graph,
    query_project_graph,
)
from .log2_histogram import Log2Histogram, LatencyTimer, record_latency, get_histogram
from .incremental_index import IncrementalIndex, ChangeType, ChangeRecord, FileWatermark
from .gatherer import GathererQueue, GathererEntry, TransactionFlags
from .prefetch import PredictivePrefetch, AccessRecord
from .bloom_filter import BloomFilter, CountingBloomFilter
from .count_min import CountMinSketch, HeavyHitters
from .rate_limiter import TokenBucket, SlidingWindowCounter
from .consistent_hash import ConsistentHashRing
from .minhash_lsh import MinHasher, LSHIndex
from .hyperloglog import HyperLogLog
from .document_ingest import (
    ConverterRegistry,
    ConversionResult,
    Converter,
    CSVConverter,
    JSONConverter,
    XMLConverter,
    HTMLConverter,
    TextConverter,
    ZipConverter,
    UnsupportedFormat,
    default_registry,
)
from .flow_dag import (
    FlowDefinition,
    FlowNode,
    FlowEval,
    FlowResult,
    FlowTrace,
    FlowExecutor,
    FlowError,
    parse_flow,
    detect_cycles,
    topological_sort,
)
from .agent_runtime import (
    Message,
    TraceEvent,
    AgentRuntime,
    Agent,
    SimpleAgent,
    ToolAction,
    ToolResult,
    Workbench,
    AgentAsTool,
)
from .graph_rag import (
    Entity,
    Relationship,
    Community,
    GraphRAGIndex,
    extract_entities,
    extract_relationships,
    detect_communities,
    build_community_summaries,
    local_query,
    global_query,
    build_index,
)
from .extension_host import (
    ExtensionManifest,
    CommandContribution,
    ToolContribution,
    ConverterContribution,
    MaintenanceCheckContribution,
    ExtensionHost,
    matches_activation,
)
from .iteration_plan import (
    IterationPlan,
    EndgameChecklist,
    ChecklistItem,
    CheckState,
    IterationPlanManager,
    default_endgame_checklist,
)
from .utility_registry import (
    Utility,
    UtilityRegistry,
    default_registry as default_utility_registry,
)
from .shell_session import (
    ShellSession,
    CommandRecord,
    OutputFrame,
    strip_ansi,
    normalize_vt,
    has_ansi,
    check_shell_safety,
)
from .source_registry import (
    Source,
    SourceRegistry,
    SourceRecord,
    SourceType,
)
from .actionability import (
    ActionabilityCheck,
    ActionabilityReport,
    ActionTrace,
    TraceRecorder,
    auto_wait,
    check_exists,
    check_visible,
    check_stable,
    check_enabled,
    check_receives_input,
)
from .changelog import (
    ChangeFile,
    ChangeKind as ChangelogChangeKind,
    ReleaseNotes,
    ChangelogManager,
    write_change_file,
)
from .kernel_plugins import (
    Kernel,
    ToolSchema,
    ToolParam,
    kernel_function,
    introspect_tool,
    validate_structured_output,
)
from .process_framework import (
    Process,
    ProcessStep,
    ProcessState,
    make_bid_process,
    make_permit_process,
)
from .agent_benchmark import (
    AgentBenchmark,
    AgentEnv,
    BenchmarkScenario,
    EpisodeResult,
    make_find_file_scenario,
    make_pdf_extract_scenario,
)
from .group_chat import (
    ChatAgent,
    GroupChatOrchestration,
    GroupChatResult,
    AgentMessage,
    make_writer_reviewer,
    make_extractor_verifier,
    make_planner_executer,
)
# B49-B60: GitHub repo research
from .query_expansion import QueryExpander, QueryVariant, SearchResult, RerankedResult
from .hash_dedup import HashDeduplicator, FileRecord, HashChange, ChangeKind
from .permission_modes import PermissionMode, PermissionManager, PermissionLevel
from .session_fork import SessionFork, SessionStore
from .dag_orchestration import DAGNode, DAGEdge, DependencyGraph
from .boundary_compaction import BoundaryAwareCompactor, CompactionResult
from .context_ops import TokenBudgetCompiler, ContextItem, ContextBOM
from .memory_evolution import MemorySkill, MemorySkillEvolver
from .extension_manifest import ExtensionCatalog, CatalogSource, ExtensionContribution
from .agent_arena import AgentArena, ArenaEntry, ArenaResult
from .daemon_mode import DaemonAgent, ClientSession, SharedMessage
from .lsp_integration import LSPManager, LSPManager as LSPClient, LSPServer
# B61-B68: Web scraping + deep research
from .content_extractor import ContentExtractor, ExtractedContent, URLDeduplicator
from .deep_research import DeepResearchEngine, DeepResearchEngine as DeepResearcher, QueryDecomposer, GapFiller
from .evidence_graph import EvidenceGraph, Source as EvidenceSource, Claim
from .critic_loop import CriticLoop, BudgetGuard, CriticResult, CriticDimension
from .parallel_fanout import ParallelFanOut, ParallelFanOut as ParallelFanout, FanOutTask, FanOutResult
from .cross_source import CrossSourceAnalyzer, CrossSourceAnalysis
from .clarification_gate import ClarificationGate, Clarification, ClarificationResult
from .research_workspace import ResearchWorkspace, ResearchBranch, ResearchArtifact
# B69-B76: Subagent/threading
from .subagent_spawner import SubAgentSpawner, SubAgentConfig, SubAgentResult
from .parallel_delegation import ParallelDelegator, DelegatedTask, DelegationResult
from .cow_state import COWStateManager, COWState
from .team_execution import TeamExecutor, TeamMember, TeamResult, TeamStrategy
from .agents_as_tools import AgentsAsTools, AgentTool, HandoffResult
from .saga_pattern import SagaOrchestrator, SagaOrchestrator as Saga, SagaStep, SagaResult
from .cavecrew import Cavecrew, CrewMember, CrewTask, CrewRole
from .spawn_scales import SpawnScaleSelector, SpawnScale, ScaleConfig
# B77-B86: Coding patterns
from .code_graph import CodeGraph, CodeNode, CodeEdge
from .structural_validator import StructuralValidator, Violation, CircuitBreaker
from .shadow_editor import ShadowEditor, EditValidation, LSPDiagnostic, LSPDiagnostic as ShadowLSPDiagnostic
from .occ_editor import OCCEditor, WriteResult
from .ralph_loop import RalphLoop, TestRun, RalphResult
from .golden_master import GoldenMaster, GoldenMasterRunner
from .refactor_transaction import RefactorTransaction, Savepoint, TransactionResult
from .task_classifier import TaskClassifier, AgentDelegator, TaskClassification, TaskComplexity, TaskDomain
from .coderank import CodeRank, CodeRankResult
from .backpressure import BackpressureMonitor, BackpressureMonitor as BackpressureController, BackpressureSignal, PressureLevel
# B87-B105: Finance / CPA / Controller patterns
from .finance import (
    ASC606DecisionDAG,
    APDuplicateDetector,
    APInvoice,
    APPayment,
    ARAgingPrioritizer,
    ARInvoice,
    AccrualEngine,
    AccrualPolicy,
    AccrualProposal,
    AgingBucket,
    AgingReport,
    BankItem,
    BankMatch,
    BankMatcher,
    BlockedTask,
    CashFlowItem,
    CashForecast,
    CashForecastWeek,
    CloseDAG,
    ClosePackageAnalyzer,
    ClosePackageInputs,
    ClosePackageResult,
    CloseTask,
    CollectionAction,
    ConstructionWIPController,
    Control,
    ControlGap,
    ControllerExceptionQueue,
    DuplicateCandidate,
    EvidenceBinder as FinanceEvidenceBinder,
    EvidenceItem as FinanceEvidenceItem,
    EvidenceReport as FinanceEvidenceReport,
    EvidenceRequest as FinanceEvidenceRequest,
    EvidenceStatus as FinanceEvidenceStatus,
    ExceptionCluster,
    FinanceException,
    FinanceProcess,
    FixedAssetRollForward,
    ForecastVariance,
    ForecastVarianceReport,
    JournalEntry,
    JournalEntryAnomalyScorer,
    JournalEntryScore,
    JobCost,
    MaterialityPolicy,
    MatchResult,
    Money,
    PayrollReconResult,
    PayrollReconciler,
    PerformanceObligation,
    QueueSummary,
    RCMRow,
    ReconciliationAccount,
    ReconciliationTriage,
    RevenueContract,
    RevenueDecision,
    ReversalProposal,
    ReviewGate,
    Risk as FinanceRisk,
    RiskControlMatrix,
    RiskControlMatrixCompiler,
    RiskLevel as FinanceRiskLevel,
    RiskScore as FinanceRiskScore,
    RollForwardResult,
    SalesUseTaxClassifier,
    Severity as FinanceSeverity,
    SoDConflict,
    SourceRef,
    TaxClassification,
    TaxLineResult,
    TaxPolicy,
    ThirteenWeekCashForecast,
    ThreeWayMatchResult,
    TieOutResult,
    Variance,
    VarianceExplanation,
    VarianceExplanationMiner,
    Vendor,
    VendorChangeEvent,
    VendorRisk,
    VendorRiskAnalyzer,
    WIPException,
    WIPReport,
    WIPRow,
    WaiverResult,
    WorkpaperTieOut,
    decimalize,
    hash_source_bytes,
    make_exception as make_finance_exception,
    month_bucket,
    normalize_invoice_number,
    normalize_vendor_name,
    stable_exception_id,
    within_tolerance,
)
# B106-B126: Construction contracts / subcontracts / independent-contractor patterns
from .construction import (
    BackchargeDocumentationGate,
    BackchargeReview,
    ChangeEvent as ConstructionChangeEvent,
    ChangeNotice,
    ChangeNoticeEngine,
    ChangeNoticeResult,
    ClassificationFactor,
    CloseoutItem,
    CloseoutMatrix,
    ConstructionIssue,
    SourceRef as ConstructionSourceRef,
    ContingentPaymentReview,
    ContingentPaymentRiskGate,
    ContingentPaymentType,
    ContractDocument,
    ContractDocumentGraph,
    ContractDocumentGraphCompiler,
    ContractRedFlagQueue,
    CoverageGap,
    CureGate,
    Deadline as ConstructionDeadline,
    DelegatedDesignGate,
    DelegatedDesignItem,
    DelegatedDesignResult,
    DelayAccelerationAnalyzer,
    DelayAnalysis,
    DelayEvent,
    DisputeProtocol,
    DisputeProtocolExtractor,
    DocumentEdge,
    FlowDownObligation,
    FlowDownResult,
    FlowDownRiskMapper,
    IndemnityInsuranceRiskSplitter,
    IndemnityScope,
    IndependentContractorClassifier,
    InsuranceRequirement,
    InsuranceRiskResult,
    Jurisdiction,
    JurisdictionOverlayResult,
    JurisdictionOverlayRouter,
    LaborUnit,
    LaborUnitDatabase,
    LienBondDeadlineCalendar,
    LienWaiverClassifier,
    LienWaiverReview,
    LowerTierFlowdownPack,
    LowerTierFlowdownResult,
    LowerTierGap,
    OSHAEmployerRole,
    OSHAMultiEmployerClassifier,
    OnboardingCompliancePack,
    OnboardingPackResult,
    OnboardingRequirement,
    OverlayRoute,
    PayApplication,
    PaymentAnalysis,
    PaymentRetainageAnalyzer,
    ProjectType,
    ProjectUse,
    RedFlag,
    RedFlagQueueResult,
    RightsCalendar,
    SafetyEvent,
    SafetyRoleResult,
    ScopeAtom,
    ScopeMatrix,
    ScopeMatrixBuilder,
    ScopeStatus,
    TerminationDefaultGate,
    TerminationMode,
    WaiverType,
    WarrantyCloseoutMatrix,
    WorkerClassificationResult,
    ReviewGate as ConstructionReviewGate,
    RiskLevel as ConstructionRiskLevel,
    # Labor units
    BUILDING_HEIGHT_FACTORS,
    CONCEALED_FACTORS,
    LADDER_HEIGHT_FACTORS,
    LABOR_COMPOSITION,
    REPETITIVE_FACTORS,
    RESIDENTIAL_DEFAULTS,
    SearchResult as LaborUnitSearchResult,
    build_database as build_labor_unit_database,
    building_height_adjustment,
    ChartSituation,
    CrewSizeEstimate,
    crew_size_curve,
    crew_size_straight_line,
    difficulty_from_chart_score,
    difficulty_from_score,
    durand_core_multiplier,
    durand_horizontal_setup_hours,
    durand_vertical_multiplier,
    LaborAdjustmentChart,
    LaborFactorScoreSheet,
    ladder_height_adjustment,
    non_working_supervision,
    repetitive_adjustment,
    residential_minutes,
    ScoreCondition,
)
# B154-B177: Acrobat-derived architecture patterns
from .acrobat_manifests import (
    UIComponent,
    ToolCommand,
    ToolManifest,
    ToolManifestLoader,
    EditionOverlay,
    ResolvedManifest,
    EditionResolver,
    HostAdapter,
    PluginSilo,
    PluginSiloRegistry,
    ResourceProvenance,
    PluginGroup,
    WebPluginVersionMap,
    DependencyEntry,
    DependencyManifest,
    TaskFilter,
    TaskFilterRegistry,
)
from .acrobat_workflows import (
    WorkflowItem,
    WorkflowInstruction,
    WorkflowCommand,
    WorkflowGroup,
    WorkflowSeparator,
    WorkflowDefinition,
    WorkflowStepResult,
    WorkflowExecutionResult,
    WorkflowExecutor,
    PolicyProfile,
    PolicyProfilePack,
)
from .acrobat_security import (
    RedactionPattern,
    RedactionCode,
    RedactionMatch,
    RedactionPatternPack,
    RedactionPackRegistry,
    default_enu_pack,
    DisqualificationRule,
    DisqualificationResult,
    DisqualificationEngine,
    default_disqual_controls,
    NativeMessagingHostManifest,
    NativeMessagingAllowlist,
)
from .acrobat_models import (
    TensorSpec,
    ModelComponent,
    ModelTarget,
    ModelManifest,
    ModelSchemaGate,
    ModelManifestRegistry,
    CompatEntry,
    CompatDecision,
    HardwareCompatTable,
    default_gpu_compat_table,
)
from .acrobat_runtime import (
    VariantRange,
    ExperimentDefinition,
    ExperimentRegistry,
    SidecarRequest,
    SidecarResult,
    SidecarWorker,
    InProcessSidecar,
    BrokerManager,
    ResourceChunk,
    ChunkLoadResult,
    ChunkedResourceLoader,
    CacheEntry,
    ScriptBytecodeCache,
)
from .acrobat_config import (
    LocaleResource,
    LocaleResourceStore,
    ServiceEndpoint,
    DispatchTable,
    ServiceDispatchRegistry,
    ThemeStyle,
    Theme,
    ThemeManager,
    default_dark_theme,
    default_light_theme,
    TelemetryEndpoint,
    TelemetryConfig,
)
from .acrobat_pipeline import (
    CrashReport,
    CrashReportResult,
    CrashReporter,
    AgentLoopCrashGuard,
    MappingRule,
    MappingResult,
    FormatMappingTable,
    PipelineStageResult,
    PipelineResult,
    PipelineStage,
    SimpleStage,
    DocumentPipeline,
    default_ocr_pipeline,
)
# Autonomous Engineer kernel (optimization engine)
from .autonomous_engineer import (
    Config as AEConfig,
    MemoryEngine,
    ExecutionSandbox,
    PerformanceWorker,
    LLMRouter,
    Scheduler as AEScheduler,
    OptimizeSpec,
)

__all__ = [
    # project_graph
    "FileNode",
    "ImportEdge",
    "ProjectGraph",
    "SymbolNode",
    "TestMapping",
    "build_project_graph",
    "query_project_graph",
    # log2_histogram (B29)
    "Log2Histogram",
    "LatencyTimer",
    "record_latency",
    "get_histogram",
    # incremental_index (B27)
    "IncrementalIndex",
    "ChangeType",
    "ChangeRecord",
    "FileWatermark",
    # gatherer (B31)
    "GathererQueue",
    "GathererEntry",
    "TransactionFlags",
    # prefetch (B33)
    "PredictivePrefetch",
    "AccessRecord",
    # bloom_filter
    "BloomFilter",
    "CountingBloomFilter",
    # count_min
    "CountMinSketch",
    "HeavyHitters",
    # rate_limiter
    "TokenBucket",
    "SlidingWindowCounter",
    # consistent_hash
    "ConsistentHashRing",
    # minhash_lsh
    "MinHasher",
    "LSHIndex",
    # hyperloglog
    "HyperLogLog",
    # document_ingest (B34)
    "ConverterRegistry",
    "ConversionResult",
    "Converter",
    "CSVConverter",
    "JSONConverter",
    "XMLConverter",
    "HTMLConverter",
    "TextConverter",
    "ZipConverter",
    "UnsupportedFormat",
    "default_registry",
    # flow_dag (B35)
    "FlowDefinition",
    "FlowNode",
    "FlowEval",
    "FlowResult",
    "FlowTrace",
    "FlowExecutor",
    "FlowError",
    "parse_flow",
    "detect_cycles",
    "topological_sort",
    # agent_runtime (B36)
    "Message",
    "TraceEvent",
    "AgentRuntime",
    "Agent",
    "SimpleAgent",
    "ToolAction",
    "ToolResult",
    "Workbench",
    "AgentAsTool",
    # graph_rag (B37)
    "Entity",
    "Relationship",
    "Community",
    "GraphRAGIndex",
    "extract_entities",
    "extract_relationships",
    "detect_communities",
    "build_community_summaries",
    "local_query",
    "global_query",
    "build_index",
    # extension_host (B38)
    "ExtensionManifest",
    "CommandContribution",
    "ToolContribution",
    "ConverterContribution",
    "MaintenanceCheckContribution",
    "ExtensionHost",
    "matches_activation",
    # iteration_plan (B39)
    "IterationPlan",
    "EndgameChecklist",
    "ChecklistItem",
    "CheckState",
    "IterationPlanManager",
    "default_endgame_checklist",
    # utility_registry (B40)
    "Utility",
    "UtilityRegistry",
    "default_utility_registry",
    # shell_session (B41)
    "ShellSession",
    "CommandRecord",
    "OutputFrame",
    "strip_ansi",
    "normalize_vt",
    "has_ansi",
    "check_shell_safety",
    # source_registry (B42)
    "Source",
    "SourceRegistry",
    "SourceRecord",
    "SourceType",
    # actionability (B43)
    "ActionabilityCheck",
    "ActionabilityReport",
    "ActionTrace",
    "TraceRecorder",
    "auto_wait",
    "check_exists",
    "check_visible",
    "check_stable",
    "check_enabled",
    "check_receives_input",
    # changelog (B44)
    "ChangeFile",
    "ChangelogChangeKind",
    "ReleaseNotes",
    "ChangelogManager",
    "write_change_file",
    # kernel_plugins (B45)
    "Kernel",
    "ToolSchema",
    "ToolParam",
    "kernel_function",
    "introspect_tool",
    "validate_structured_output",
    # process_framework (B46)
    "Process",
    "ProcessStep",
    "ProcessState",
    "make_bid_process",
    "make_permit_process",
    # agent_benchmark (B47)
    "AgentBenchmark",
    "AgentEnv",
    "BenchmarkScenario",
    "EpisodeResult",
    "make_find_file_scenario",
    "make_pdf_extract_scenario",
    # group_chat (B48)
    "ChatAgent",
    "GroupChatOrchestration",
    "GroupChatResult",
    "AgentMessage",
    "make_writer_reviewer",
    "make_extractor_verifier",
    "make_planner_executer",
    # B49-B60: GitHub repo research
    "QueryExpander",
    "QueryVariant",
    "SearchResult",
    "RerankedResult",
    "HashDeduplicator",
    "FileRecord",
    "HashChange",
    "ChangeKind",
    "PermissionMode",
    "PermissionManager",
    "PermissionLevel",
    "SessionFork",
    "SessionStore",
    "DAGNode",
    "DAGEdge",
    "DependencyGraph",
    "BoundaryAwareCompactor",
    "CompactionResult",
    "TokenBudgetCompiler",
    "ContextItem",
    "ContextBOM",
    "MemorySkill",
    "MemorySkillEvolver",
    "ExtensionCatalog",
    "CatalogSource",
    "ExtensionContribution",
    "AgentArena",
    "ArenaEntry",
    "ArenaResult",
    "DaemonAgent",
    "ClientSession",
    "SharedMessage",
    "LSPManager",
    "LSPClient",
    "LSPServer",
    # B61-B68: Web scraping + deep research
    "ContentExtractor",
    "ExtractedContent",
    "URLDeduplicator",
    "DeepResearchEngine",
    "DeepResearcher",
    "QueryDecomposer",
    "GapFiller",
    "EvidenceGraph",
    "EvidenceSource",
    "Claim",
    "CriticLoop",
    "BudgetGuard",
    "CriticResult",
    "CriticDimension",
    "ParallelFanOut",
    "ParallelFanout",
    "FanOutTask",
    "FanOutResult",
    "CrossSourceAnalyzer",
    "CrossSourceAnalysis",
    "ClarificationGate",
    "Clarification",
    "ClarificationResult",
    "ResearchWorkspace",
    "ResearchBranch",
    "ResearchArtifact",
    # B69-B76: Subagent/threading
    "SubAgentSpawner",
    "SubAgentConfig",
    "SubAgentResult",
    "ParallelDelegator",
    "DelegatedTask",
    "DelegationResult",
    "COWStateManager",
    "COWState",
    "TeamExecutor",
    "TeamMember",
    "TeamResult",
    "TeamStrategy",
    "AgentsAsTools",
    "AgentTool",
    "HandoffResult",
    "SagaOrchestrator",
    "Saga",
    "SagaStep",
    "SagaResult",
    "Cavecrew",
    "CrewMember",
    "CrewTask",
    "CrewRole",
    "SpawnScaleSelector",
    "SpawnScale",
    "ScaleConfig",
    # B77-B86: Coding patterns
    "CodeGraph",
    "CodeNode",
    "CodeEdge",
    "StructuralValidator",
    "Violation",
    "CircuitBreaker",
    "ShadowEditor",
    "EditValidation",
    "LSPDiagnostic",
    "ShadowLSPDiagnostic",
    "OCCEditor",
    "WriteResult",
    "RalphLoop",
    "TestRun",
    "RalphResult",
    "GoldenMaster",
    "GoldenMasterRunner",
    "RefactorTransaction",
    "Savepoint",
    "TransactionResult",
    "TaskClassifier",
    "AgentDelegator",
    "TaskClassification",
    "TaskComplexity",
    "TaskDomain",
    "CodeRank",
    "CodeRankResult",
    "BackpressureMonitor",
    "BackpressureController",
    "BackpressureSignal",
    "PressureLevel",
    # B87-B105: Finance / CPA / Controller patterns
    "ASC606DecisionDAG",
    "APDuplicateDetector",
    "APInvoice",
    "APPayment",
    "ARAgingPrioritizer",
    "ARInvoice",
    "AccrualEngine",
    "AccrualPolicy",
    "AccrualProposal",
    "AgingBucket",
    "AgingReport",
    "BankItem",
    "BankMatch",
    "BankMatcher",
    "BlockedTask",
    "CashFlowItem",
    "CashForecast",
    "CashForecastWeek",
    "CloseDAG",
    "ClosePackageAnalyzer",
    "ClosePackageInputs",
    "ClosePackageResult",
    "CloseTask",
    "CollectionAction",
    "ConstructionWIPController",
    "Control",
    "ControlGap",
    "ControllerExceptionQueue",
    "DuplicateCandidate",
    "FinanceEvidenceBinder",
    "FinanceEvidenceItem",
    "FinanceEvidenceReport",
    "FinanceEvidenceRequest",
    "FinanceEvidenceStatus",
    "ExceptionCluster",
    "FinanceException",
    "FinanceProcess",
    "FixedAssetRollForward",
    "ForecastVariance",
    "ForecastVarianceReport",
    "JournalEntry",
    "JournalEntryAnomalyScorer",
    "JournalEntryScore",
    "JobCost",
    "MaterialityPolicy",
    "MatchResult",
    "Money",
    "PayrollReconResult",
    "PayrollReconciler",
    "PerformanceObligation",
    "QueueSummary",
    "RCMRow",
    "ReconciliationAccount",
    "ReconciliationTriage",
    "RevenueContract",
    "RevenueDecision",
    "ReversalProposal",
    "ReviewGate",
    "FinanceRisk",
    "RiskControlMatrix",
    "RiskControlMatrixCompiler",
    "FinanceRiskLevel",
    "FinanceRiskScore",
    "RollForwardResult",
    "SalesUseTaxClassifier",
    "FinanceSeverity",
    "SoDConflict",
    "SourceRef",
    "TaxClassification",
    "TaxLineResult",
    "TaxPolicy",
    "ThirteenWeekCashForecast",
    "ThreeWayMatchResult",
    "TieOutResult",
    "Variance",
    "VarianceExplanation",
    "VarianceExplanationMiner",
    "Vendor",
    "VendorChangeEvent",
    "VendorRisk",
    "VendorRiskAnalyzer",
    "WIPException",
    "WIPReport",
    "WIPRow",
    "WaiverResult",
    "WorkpaperTieOut",
    "decimalize",
    "hash_source_bytes",
    "make_finance_exception",
    "month_bucket",
    "normalize_invoice_number",
    "normalize_vendor_name",
    "stable_exception_id",
    "within_tolerance",
    # B106-B126: Construction contracts / subcontracts / independent-contractor patterns
    "BackchargeDocumentationGate",
    "BackchargeReview",
    "ConstructionChangeEvent",
    "ChangeNotice",
    "ChangeNoticeEngine",
    "ChangeNoticeResult",
    "ClassificationFactor",
    "CloseoutItem",
    "CloseoutMatrix",
    "ConstructionIssue",
    "ConstructionSourceRef",
    "ContingentPaymentReview",
    "ContingentPaymentRiskGate",
    "ContingentPaymentType",
    "ContractDocument",
    "ContractDocumentGraph",
    "ContractDocumentGraphCompiler",
    "ContractRedFlagQueue",
    "CoverageGap",
    "CureGate",
    "ConstructionDeadline",
    "DelegatedDesignGate",
    "DelegatedDesignItem",
    "DelegatedDesignResult",
    "DelayAccelerationAnalyzer",
    "DelayAnalysis",
    "DelayEvent",
    "DisputeProtocol",
    "DisputeProtocolExtractor",
    "DocumentEdge",
    "FlowDownObligation",
    "FlowDownResult",
    "FlowDownRiskMapper",
    "IndemnityInsuranceRiskSplitter",
    "IndemnityScope",
    "IndependentContractorClassifier",
    "InsuranceRequirement",
    "InsuranceRiskResult",
    "Jurisdiction",
    "JurisdictionOverlayResult",
    "JurisdictionOverlayRouter",
    "LaborUnit",
    "LaborUnitDatabase",
    "LaborUnitSearchResult",
    "LienBondDeadlineCalendar",
    "LienWaiverClassifier",
    "LienWaiverReview",
    "LowerTierFlowdownPack",
    "LowerTierFlowdownResult",
    "LowerTierGap",
    "OSHAEmployerRole",
    "OSHAMultiEmployerClassifier",
    "OnboardingCompliancePack",
    "OnboardingPackResult",
    "OnboardingRequirement",
    "OverlayRoute",
    "PayApplication",
    "PaymentAnalysis",
    "PaymentRetainageAnalyzer",
    "ProjectType",
    "ProjectUse",
    "RedFlag",
    "RedFlagQueueResult",
    "RightsCalendar",
    "SafetyEvent",
    "SafetyRoleResult",
    "ScopeAtom",
    "ScopeMatrix",
    "ScopeMatrixBuilder",
    "ScopeStatus",
    "TerminationDefaultGate",
    "TerminationMode",
    "WaiverType",
    "WarrantyCloseoutMatrix",
    "WorkerClassificationResult",
    "ConstructionReviewGate",
    "ConstructionRiskLevel",
    "BUILDING_HEIGHT_FACTORS",
    "CONCEALED_FACTORS",
    "LADDER_HEIGHT_FACTORS",
    "LABOR_COMPOSITION",
    "REPETITIVE_FACTORS",
    "RESIDENTIAL_DEFAULTS",
    "build_labor_unit_database",
    "building_height_adjustment",
    "difficulty_from_chart_score",
    "difficulty_from_score",
    "ladder_height_adjustment",
    "repetitive_adjustment",
    "residential_minutes",
    "ChartSituation",
    "CrewSizeEstimate",
    "crew_size_curve",
    "crew_size_straight_line",
    "durand_core_multiplier",
    "durand_horizontal_setup_hours",
    "durand_vertical_multiplier",
    "LaborAdjustmentChart",
    "LaborFactorScoreSheet",
    "non_working_supervision",
    "ScoreCondition",
    # acrobat_manifests (B154-B156, B162, B168, B171)
    "UIComponent",
    "ToolCommand",
    "ToolManifest",
    "ToolManifestLoader",
    "EditionOverlay",
    "ResolvedManifest",
    "EditionResolver",
    "HostAdapter",
    "PluginSilo",
    "PluginSiloRegistry",
    "ResourceProvenance",
    "PluginGroup",
    "WebPluginVersionMap",
    "DependencyEntry",
    "DependencyManifest",
    "TaskFilter",
    "TaskFilterRegistry",
    # acrobat_workflows (B157-B158)
    "WorkflowItem",
    "WorkflowInstruction",
    "WorkflowCommand",
    "WorkflowGroup",
    "WorkflowSeparator",
    "WorkflowDefinition",
    "WorkflowStepResult",
    "WorkflowExecutionResult",
    "WorkflowExecutor",
    "PolicyProfile",
    "PolicyProfilePack",
    # acrobat_security (B159, B161, B173)
    "RedactionPattern",
    "RedactionCode",
    "RedactionMatch",
    "RedactionPatternPack",
    "RedactionPackRegistry",
    "default_enu_pack",
    "DisqualificationRule",
    "DisqualificationResult",
    "DisqualificationEngine",
    "default_disqual_controls",
    "NativeMessagingHostManifest",
    "NativeMessagingAllowlist",
    # acrobat_models (B160, B172)
    "TensorSpec",
    "ModelComponent",
    "ModelTarget",
    "ModelManifest",
    "ModelSchemaGate",
    "ModelManifestRegistry",
    "CompatEntry",
    "CompatDecision",
    "HardwareCompatTable",
    "default_gpu_compat_table",
    # acrobat_runtime (B163-B165, B175)
    "VariantRange",
    "ExperimentDefinition",
    "ExperimentRegistry",
    "SidecarRequest",
    "SidecarResult",
    "SidecarWorker",
    "InProcessSidecar",
    "BrokerManager",
    "ResourceChunk",
    "ChunkLoadResult",
    "ChunkedResourceLoader",
    "CacheEntry",
    "ScriptBytecodeCache",
    # acrobat_config (B166-B167, B170, B177)
    "LocaleResource",
    "LocaleResourceStore",
    "ServiceEndpoint",
    "DispatchTable",
    "ServiceDispatchRegistry",
    "ThemeStyle",
    "Theme",
    "ThemeManager",
    "default_dark_theme",
    "default_light_theme",
    "TelemetryEndpoint",
    "TelemetryConfig",
    # acrobat_pipeline (B169, B174, B176)
    "CrashReport",
    "CrashReportResult",
    "CrashReporter",
    "AgentLoopCrashGuard",
    "MappingRule",
    "MappingResult",
    "FormatMappingTable",
    "PipelineStageResult",
    "PipelineResult",
    "PipelineStage",
    "SimpleStage",
    "DocumentPipeline",
    "default_ocr_pipeline",
    # autonomous_engineer (optimization kernel)
    "AEConfig",
    "MemoryEngine",
    "ExecutionSandbox",
    "PerformanceWorker",
    "LLMRouter",
    "AEScheduler",
    "OptimizeSpec",
]
